=== First steps

Let's start with some basic Terraform commands.
Run the following commands on the "Shell" tab.

Check the version of Terraform running on your machine:

```
terraform version
```

You can always get help if you're curious about command syntax:

```
terraform --help
```

#Connecting Terraform to AWS

In order to authenticate to AWS and build resources, Terraform requires you to provide a set of credentials, backed by an appropriate IAM policy.

For this training environment, we have prepared some temporary AWS credentials and stored them as environment variables. Terraform will automatically read and use the environment variables that are configured in your shell environment.

Run the following commands on the "Shell" tab:

```
echo $AWS_ACCESS_KEY_ID
echo $AWS_SECRET_ACCESS_KEY
```
You should see valid AWS keys. If not, return to the track home page by clicking the **Close** button, stop the track, and then restart it.


IMPORTANT: *Do not ever store your credentials in source code files*, as they can be accidentally exposed or copied to a public repository.

